### ISSUE TITLE
Scss support!

### ISSUE THREAD

**Issue by VivianSolide** [mc100s/mern-boilerplate#3]
Adding bootstrap 4
and...
```scss
body {
	@include media-breakpoint-up(md) {
		font-size: 1.8rem;
		background-color: #ff6666;
	}
	@include media-breakpoint-down(lg) {
		font-size: 1.6rem;
		background-color: #ffb266;
	}
	@include media-breakpoint-down(md) {
		font-size: 1.4rem;
		background-color: #ffff66;
	}
	@include media-breakpoint-down(sm) {
		font-size: 1.2rem;
		background-color: #b2ff66;
	}
	@include media-breakpoint-down(xs) {
		font-size: 1rem;
		background-color: #b2b266;
	}
}

```
$ sass style.scss App.css --watch
